#!/usr/bin/env bash

# slick herbstluftwm config

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#979797'

# remove all existing keybindings
hc keyunbind --all

# startup apps
pkill tint2
pkill xbindkeys
tint2 -c ~/.config/tint2/fbrwn1/tint2rc-border &
tint2 -c ~/.config/tint2/fbrwn1/tint2rc-ws &
tint2 -c ~/.config/tint2/fbrwn1/tint2rc-task &
tint2 -c ~/.config/tint2/fbrwn1/tint2rc-clockbatt &
compton &
xrdb ~/.Xresources &
xbindkeys &
pactl set-sink-volume 0 90% &
feh --bg-fill ~/.wallpaper.png --no-fehbg &
xinput set-prop "SynPS/2 Synaptics TouchPad" "Device Enabled" 0

# Mod1=alt Mod4=super
Mod=Mod4

# keybindings
hc keybind $Mod-Shift-Delete quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-q close_or_remove
hc keybind $Mod-Shift-q close_and_remove

# shortcuts
hc keybind $Mod-Return spawn urxvt
hc keybind $Mod-d spawn dmenu_run -fn kakwafont -p $ -nb '#4a4a4a' -sb '#979797'
hc keybind $Mod-w spawn firefox-esr
hc keybind $Mod-Shift-w spawn google-chrome-stable
hc keybind $Mod-t spawn urxvt -e htop
hc keybind $Mod-r spawn urxvt -e ranger
hc keybind $Mod-Shift-t spawn urxvt -e rainbowstream
hc keybind $Mod-m spawn urxvt -e cmus
hc keybind $Mod-c spawn urxvt -e calcurse
hc keybind Control-Alt-l spawn i3lock -f -i ~/Pictures/hlwm/i3lock.png

# screenshot
hc keybind Print spawn scrot 'scrot_%Y-%m-%d-%S_$wx$h.png'

# padding
hc pad 0 37 0 0 0

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-y       split   left    0.5
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-i       split   top     0.5
hc keybind $Mod-o       split   right   0.5

# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.01
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

hc keybind $Mod-g cycle_value window_gap 10 0
hc keybind $Mod-Shift-g cycle_value frame_transparent_width 0 4

# layouting
hc keybind $Mod-BackSpace remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle

hc keybind $Mod-b load '(split horizontal:0.660000:1 (clients vertical:0)
(split vertical:0.610000:1 (clients vertical:0) (clients vertical:0 0x1600009)))'
hc keybind $Mod-n load '(split horizontal:0.850000:0
(split horizontal:0.200000:1
(clients vertical:0)
(clients grid:0))
(clients vertical:0))
'               # load predefined layout
# center all other gimp windows on gimp tag
hc rule class=Gimp tag=gimp index=01 pseudotile=on
hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' \
pseudotile=off
hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
hc rule class=Gimp windowrole=gimp-dock focus=off index=1

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
#hc keybind $Mod-c cycle
#hc keybind $Mod-i jumpto urgent

# tags
tag_names=("  " "  " "  ")
tag_keys=( {1..3} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done


# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#'
hc set frame_border_normal_color '#'
hc set frame_bg_normal_color '#979797'
hc set frame_bg_active_color '#FFFFFF'
hc set frame_normal_opacity 50
hc set frame_active_opacity 50
hc set frame_border_width 0
hc set always_show_frame 1
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0

hc attr theme.active.color '#968D6F'
hc attr theme.normal.color '#3C3D39'
hc attr theme.urgent.color orange
hc attr theme.inner_width 0
hc attr theme.inner_color gray
hc attr theme.border_width 2
hc attr theme.floating.border_width 2
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#'
hc attr theme.active.outer_color '#'
hc attr theme.background_color '#'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 1


# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
#panel=~/.config/herbstluftwm/panel.sh
#[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
#    "$panel" $monitor &
#done
